fix(ProfessorRolesTable): Don't automatically default to 'student' ro…
cornell-dti/office-hours pull request #377
Opened 2020-09-09 01:46 UTC by ngwattcos

…le when clicking out of role dropdown.

Fixes #376.
### Summary 

### Test Plan 

Open AdminView (/admin) or the professor role table when enrolled as a professor. Click on a TA/professor user's dropdown role, then click outside. User's role should not change.

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2020-09-10 04:26 UTC, ewlsh requested changes

2020-09-10 04:26 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +            onChange={(e, newValue) => {
I think part of the issue is that we aren't setting an initial `value={user.role}` on this component. This works because the initial value is probably undefined (or similar) - we should still implement this check to avoid unnecessarily updating.

2020-09-10 04:26 UTC, ewlsh commented
Another guard we should perhaps also consider is preventing the user from demoting them self. I accidentally did this once, there is no warning and this bug made it a lot worse.

2020-09-10 05:02 UTC, ngwattcos commented
@ewlsh I added the guard so that users with the ability to change roles can't demote themself to students.

Interestingly, the issue isn't with user.role, since it can only be "professor" | "student" | "ta". The problem was with newValue.role because it was a string that could be "Student", "TA", "Professor." It turns out if you cast newValue.value as a ```FireCourseRole```, it automatically converts the string to the proper case as well.

2020-09-10 05:02 UTC, ngwattcos commented on src/components/includes/ProfessorRolesTable.tsx
> +            onChange={(e, newValue) => {
See below comment.

2020-09-10 14:43 UTC, ewlsh requested changes

2020-09-10 14:43 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +                    if (user.userId !== ownUser?.userId || newValueRole !== "student") {
I think this line still permits professors to convert themselves to TAs, which isn't ideal.

We could use `deactivate={}` to prevent user interaction and perhaps move the `user.userId !== ownUser?.userId` check out of the component and simply pass it as a boolean.

That will also prevent any interaction and grey out the dropdown.

2020-09-10 14:43 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +            onChange={(e, newValue) => {
I did some digging.

We need to set `defaultValue` instead of `text`. [In the CSS here](https://github.com/cornell-dti/office-hours/blob/e793f6043e46815aa1e8849e5c93ed8e196b7c62/src/styles/professor/ProfessorRoles.scss#L4) it forces the dropdown text to always display in capital case. This is why we get `Ta` instead of `TA`. Part of the confusion of the checks you're doing in `onChange` stems from the fact that we don't set the initial value of the dropdown correctly and we intermix text/value.

We should probably remove that CSS.

2020-09-10 14:43 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +                            <RoleDropdown ownUser={self} user={u} course={course} />
If we do the userId check here we avoid passing the entire user object.

2020-09-10 14:44 UTC, ewlsh commented
@ngwattcos casting can never change the underlying value, what is happening is the way the text field is being displayed is distorted by CSS.

The CSS forces it to always display capital case, which is why we get `Ta` instead of `TA`. We just need to adhere to the dropdown spec better.

2020-09-10 14:46 UTC, ngwattcos commented on src/components/includes/ProfessorRolesTable.tsx
> +                    if (user.userId !== ownUser?.userId || newValueRole !== "student") {
Agreed, we should probably disable professor level users from editing themselves entirely

2020-09-10 14:50 UTC, ngwattcos commented
@ewlsh thanks for the info!

2020-09-10 14:52 UTC, ewlsh commented
dropdown info source: https://react.semantic-ui.com/modules/dropdown/

2020-10-08 17:54 UTC, ngwattcos commented
@ewlsh Whoops, forgot about this one. I've added the ```defaultText``` value and prevented professors from demoting themselves. I've tested that users won't demote other users by accident when cancelling.

2020-10-11 16:42 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +            text={toDisplayCase(user.role)}
You should just be able to remove `text=` as the options array associates text with the role value.

2020-10-11 16:43 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +                if (isSelf) {
TAs don't need to be able to demote themselves, and they can't promote themselves.

2020-10-11 16:44 UTC, ewlsh commented on src/components/includes/ProfessorRolesTable.tsx
> +                    if (user.role !== 'professor') {
I would keep this check just-in-case, but I'd also add a `deactivate` property to the dropdown when it is self.

2020-10-11 20:11 UTC, ngwattcos commented on src/components/includes/ProfessorRolesTable.tsx
> +                    if (user.role !== 'professor') {
Gotcha. Now it's ```disabled``` only for your own dropdown.

2020-10-11 22:01 UTC, ngwattcos commented on src/components/includes/ProfessorRolesTable.tsx
> +            text={toDisplayCase(user.role)}
👍

2020-10-11 22:02 UTC, ngwattcos commented on src/components/includes/ProfessorRolesTable.tsx
> +                if (isSelf) {
Hopefully the new logic makes this cleaner

2020-10-25 19:13 UTC, triple-jay approved these changes
Looks good! I tested on the /admin page with your test plan and it works as it should. Also, your code style looks clear and good.

2020-10-25 19:35 UTC, merged