Implemented TA comments
cornell-dti/office-hours pull request #396
Opened 2020-10-02 03:25 UTC by abcdefguan

### Summary 

TA comments have been implemented as per the design provided.

There are a few issues:

- No tooltip with "Comment" displays when mousing over the comment icon. Tooltips are difficult to get code in CSS so I'm leaving it out for now.
- No design was given for how TA comments will look on the student side. It will currently display as "TA Comment: <comment>" at the bottom of the question. This can be improved in future.
- I also used a different gray for the hover of the comment icon because the original gray was not contrasting enough.
- The comment icon is also different from the design icon because semantic UI only provides this comment icon.

New Features:
- Implemented TA comments

### Test Plan 

- Tested that TA can edit a comment, cancel a comment edit and save a comment on the TA side.
- Have not checked student side yet.
- Will probably conduct a Queue Me In test or something in order to check that this works.

### Notes 

### Breaking Changes 

Firebase schema change (requires migration plan)

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

No migration plan is necessary because my code handles undefined TA comments

2020-10-02 04:37 UTC, ngwattcos requested changes

2020-10-02 04:37 UTC, ngwattcos commented on src/components/includes/SessionQuestion.tsx
> +                                src={user.photoUrl || '/placeholder.png'}
This causes a crash on the student-side. I think replacing with user?.photoUrl should do the trick

2020-10-02 04:37 UTC, ngwattcos commented on src/components/includes/SessionQuestion.tsx
> +                    <button className="commentBtn" onClick={this.toggleTAComment} type="button">
Have we received designs from the designers for this component yet? If not, I wonder if you could change the implementation slightly to something more like a traditional text box. Here are my suggestions:
- the textbox should already be there so that the TA can readily enter the comments
- The icon is fine; it just bring's the focus to the textbox
- The TA should not have to click "edit" to begin typing into the textbox
- hitting Enter key should automatically save the changes as well

On the other hand, if this is what the designers decided on, then go for it.

2020-10-03 16:16 UTC, abcdefguan commented on src/components/includes/SessionQuestion.tsx
> +                    <button className="commentBtn" onClick={this.toggleTAComment} type="button">
This was the design provided. You should talk to the designers about this.

2020-10-03 20:36 UTC, ngwattcos commented
Oh no! Something weird is happening with the formatting:
![image](https://user-images.githubusercontent.com/18223523/95001296-918b7080-0596-11eb-830e-56974948ec34.png)

2020-10-03 21:01 UTC, ngwattcos approved these changes
Thanks for implementing this feature! It looks good to me.

2020-10-03 21:20 UTC, abcdefguan commented
The feature has been improved to allow both students and TAs to comment. This PR introduces a huge change and should be tested during subteam meetings to ensure correctness. There are a bunch of minor outstanding CSS issues with this PR which have been highlighted in the Issues.

2020-10-15 16:46 UTC, merged