added the netid of students after name in ta view
cornell-dti/office-hours pull request #414
Opened 2020-10-24 00:49 UTC by vladiatrinh

### Summary 

When there are questions from students in the TA view, the component now also displays the students' netid so the TA can easily contact them if necessary. 

### Test Plan 

I ran QMI locally and created a new account where I was a student. There I added a question and made sure that in my original account, the TA view showed my email address up until the @ symbol. For Cornell emails, this with display their netid properly.

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2020-10-24 13:06 UTC, nada-attia requested changes
looks great! but before I can approve, can you fix the linter issue thats causing your build to fail? (run `yarn lint` to see the issue)

edit: also, there seems to be a merge conflict that needs to be resolved

2020-10-25 00:31 UTC, abcdefguan commented on src/components/includes/SessionQuestion.tsx
> +                                {asker.firstName + ' ' + asker.lastName + ' (' + asker.email.slice(0,asker.email.indexOf('@')) + ')'}
This will crash if the email somehow doesn't contain @. You could make it more robust if you want, but I think this should be fine.

2020-10-25 00:34 UTC, abcdefguan reviewed
The feature appears to work correctly.
I think we also discussed letting students see TA net IDs when a TA is assigned to them and it would be good to implement that here.
However, I noticed that students can't actually see which TA assigned them. In fact, this actually throws a firebase error where the student doesn't have enough permissions to access the TA's information for some reason. Do you see this bug on your end?

2020-10-25 17:08 UTC, abcdefguan approved these changes

2020-10-25 17:34 UTC, nada-attia approved these changes

2020-10-25 17:35 UTC, merged