Implemented redesign for new top bar in the student and ta view
cornell-dti/office-hours pull request #445
Opened 2020-12-10 23:08 UTC by vladiatrinh

### Summary 
Redesigned the top bar by moving the course toggle from the CalendarView to the TopBar and changing the QMI Logo.

Cristie's figma design for reference: https://www.figma.com/file/h0kMHuGjX9QCtZ0Y6rUbDj/Fall-2020?node-id=709%3A143

I also fixed a weird bug (which is in production QMI too), where if you click anywhere on the top bar, the modal for the log out menu appears. Now, it only appears if you click the user profile div. 

### Test Plan 

- Enroll in multiple courses in QMI where you have different roles, TA and student, for example.
- Make sure that the new toggle shows up on all pages
- When clicked, a menu should pop up with all the classes you are enrolled in. Your current class should have a check mark next to it.
- If you aren't currently in a specific course view, the toggle should just say "Courses." This happens if you're on the Course Selection page.

### Notes 

The top bar for the professor view is not implemented yet. In the future, there should be another toggle that replaces the Switch View button in the Logout menu.

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2020-12-11 22:02 UTC, ngwattcos commented
Looks very good in general! There are a couple things I want to add here:

**Interaction**
The dropdown should collapse if you click on anything except for the dropdown. For example, if the dropdown for INFO 4998 is open, and you click either 1) a white space, or 2) the other dropdown, it will collapse INFO 4998.

**Alignment**
This probably wasn't thought up of during the design but switching from student view to professor view could cause alignment to shift when a scroll bar appears (it's a bit jarring visually but not egregious). See INFO 4998 for example.

**Naming**
I feel that the name Student for the student view is a bit iffy, since 1) all users can see some form of the queue and 2) students vs. tas/professors see a different view.

Do you mind if we bring these questions back to design?

2020-12-16 14:22 UTC, abcdefguan commented
Spotted a bug relating to this PR. Please look at issue #448 . I believe this is an old issue though so it'd be nice to fix this issue while you're at it.

2020-12-16 14:29 UTC, abcdefguan commented
Which Queue Me In logo is correct?
Is it this one?
![Logo](https://user-images.githubusercontent.com/9957585/102361242-027cda80-3f81-11eb-8e77-75cd9da6b211.png)
Or this one
![QLogo2](https://user-images.githubusercontent.com/9957585/102361245-04469e00-3f81-11eb-82dd-8c4d59f1b2e5.png)

I've got the feeling that 
![QLogo2](https://user-images.githubusercontent.com/9957585/102361245-04469e00-3f81-11eb-82dd-8c4d59f1b2e5.png)
is the correct logo, but this PR appears to use
![Logo](https://user-images.githubusercontent.com/9957585/102361242-027cda80-3f81-11eb-8e77-75cd9da6b211.png)
as its logo

2020-12-16 14:39 UTC, abcdefguan commented on src/components/includes/TopBar.tsx
> +import Logo from '../../media/Logo.svg';
import Logo from '../../media/QLogo2.svg';

2020-12-16 14:44 UTC, abcdefguan commented on src/components/includes/TopBar.tsx
>      useEffect(() => setImage(userPhotoUrl), [userPhotoUrl]);
I'm not sure that this line of code does anything because it doesn't actually introduce any side effects (outside of React)

2020-12-16 14:50 UTC, abcdefguan commented
Looks good to me. Great Job. Some minor issues you should clear up then your PR is good to go.

2020-12-17 05:13 UTC, ngwattcos requested changes
Hi Vladia, nice work on incorporating the design revisions!

There are still a few other things left to add (also there's a merge conflict in one file. Let me know if you need any help resolving it!):
For each dropdown, the dropdown should close as soon as you click off the dropdown (i.e., whitespace, the other dropdown, etc.)

2021-01-25 02:09 UTC, ngwattcos approved these changes

2021-01-25 02:13 UTC, ngwattcos requested changes
Nice work, @triple-jay! Unfortunately it seems that the Queue/Dashboard dropdown also needs to be collapsed when not clicking on the dropdown.

In addition, there is still a problem with #448 - it displays courses that have ended ((in the screenshot below, CS 3110 has already ended):
![image](https://user-images.githubusercontent.com/18223523/105653105-ed04a580-5e88-11eb-9472-180c60f13b6c.png)

You can fix this by referring to lines 26-32 in `CourseSelection.tsx`, which filter courses by `endDate`.

2021-01-26 03:28 UTC, ngwattcos approved these changes
Looks good to me! Just be sure to rebase with the newest commits from master,

2021-01-27 04:44 UTC, ngwattcos approved these changes
LGTM

2021-01-27 04:55 UTC, merged