Added TA and student comments to discussion questions
cornell-dti/office-hours pull request #446
Opened 2020-12-12 02:38 UTC by triple-jay

### Summary 
Added TA and student comments to discussion questions, and made slight style changes on the discussion question component.

I implemented TA and student comments so both TAs and students can comment on discussion questions, which other people can also see. I also made some slight style changes on the upvote button. I made slight changes in the types for FireQuestion to give the capability of comments to discussion questions.

### Test Plan 
- Add a comment as a student on a discussion question
- Add a comment as a TA on a discussion question
- See if you can see the student comment as a TA, and vice versa

### Notes 

### Breaking Changes 

None

I updated existing types in `/src/components/types/`

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2020-12-17 03:41 UTC, ewlsh requested changes
Looking good thus far, I made some comments on style and potential issues!

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +import Linkify from 'linkifyjs/react';
The proper way to do this is to declare:

```ts
declare module "linkifyjs/react" {
    var _: any;
    export default _;
}
```

an "any" module like this. You can then build types over time.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
>      // const studentNoShow = () => {
I know these aren't part of the PR, but in general avoid leaving commented code in the files you own.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +        firestore.doc(`questions/${question.questionId}`).update(update);
You should handle the promise error here with `.catch` and maybe do something on success.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +
Unnecessary new line.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                        alt={user ? `${user.firstName} ${user.lastName}` : 'unknown user'}
Is 'unknown user' helpful for someone who doesn't see the image?

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                    evt.preventDefault();
Why does the default event need to be prevented here?

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                <Linkify className={'Question' + props.studentCSS} tagName="p">
Prefer template strings over string concat: `Question ${props.studentCSS || ''}` (also handle if it can be falsey)

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                <Linkify className={'Question' + props.studentCSS} tagName="p">
(it can be falsy because you have it optional with `?`

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +            outline: none;
Don't disable outlines, it breaks keyboard navigation.

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +            background-color: Transparent;
`transparent`

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +        .commentBtn:hover {
Prefer `&:hover {}` as a child of `.commentBtn`

```scss
.commentBtn {
   &:hover {
   }
}
```

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +                width: 90%;
In general, I avoid percentage widths unless there is a good reason to use them. What is the reasoning here?

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +        //   padding: 10px 0px 0px 15px;
Commented code.

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +        object-fit: cover;
Be careful with cover fits, make sure it adapts to all ratios and doesn't break under very skinny or very tall screens.

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +        width: 78%;
Why 78%?

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +        text-align: right;
If you're just aligning items you can use the various `justify-contents`, `align-items`, etc. variants instead of text alignment. If you need to align text, all good.

2020-12-17 03:41 UTC, ewlsh commented on src/styles/session/DiscussionQuestion.scss
> +            font-size: 17px;
Generally, prefer `rem` or `em` for font sizing so they scale correctly.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                {comment !== "" && comment !== undefined ? comment : "Add a comment..."}
I'd just do a falsy check here, `!!comment` or you can do `comment || "Add a comment..."`

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                        questionComment(newComment, props.isTA);
You don't need to pass `props.isTA` here, you can reference it in the function.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +                    <CommentBox
If only one needs to be true I'd selectively render instead of passing both.

2020-12-17 03:41 UTC, ewlsh commented on src/components/includes/DiscussionQuestion.tsx
> +    const user = props.user;
You can use destructuring here.

`const {user = null } = props;`

2021-02-04 14:13 UTC, triple-jay commented on src/styles/session/DiscussionQuestion.scss
> +                width: 90%;
I wanted the text area to resize with the comment body proportionately.

2021-02-05 01:45 UTC, ngwattcos approved these changes
Excellent work, Jeremy! I can add and edit comments on both the TA and student side.

2021-02-05 03:13 UTC, merged