Fixes issue #477
cornell-dti/office-hours pull request #480
Opened 2021-01-28 19:58 UTC by asharonbaltazar

### Summary 
Addresses issue #477 

Changed `a` tags to `div`s and removed the `href`, supplementing with `useHistory` hook from `react-router`. Changed respective SCSS. Added new click handler function for brevity in the actual JSX. 

### Test Plan 
Open to ideas.

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2021-01-28 19:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/office-hours?pullRequest=480) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/office-hours?pullRequest=480) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/office-hours?pullRequest=480) it.</sub>

2021-01-29 19:46 UTC, ngwattcos requested changes
Looks good, @asharonbaltazar ! Thanks for taking on this PR.

There is one tiny styling nit: please see the comment

2021-01-29 19:46 UTC, ngwattcos requested changes

2021-01-29 19:46 UTC, ngwattcos commented on src/components/includes/CalendarHeader.tsx
> +import {useHistory} from 'react-router'
Please add a space between the brackets for `useHistory`.

2021-01-29 19:47 UTC, asharonbaltazar commented on src/components/includes/CalendarHeader.tsx
> +import {useHistory} from 'react-router'
Oh my, I thought that should've been automatic. No problem. Coming right up.

2021-01-29 21:48 UTC, ngwattcos approved these changes
LGTM

2021-03-30 01:49 UTC, closed without merging