Admin course creation bugfix
cornell-dti/office-hours pull request #593
Opened 2021-11-12 01:18 UTC by Archit404Error

### Summary

Fixed bug where term and year values were switched and cleaned up the form itself. Since semester (FA21) is simply the term(FA) + year(21), it didn't make sense to have the admin re-enter this info. Also added form input validation.

### Test Plan

Created several sample courses and ensured they worked/validated properly.

### Notes

In the future the form itself should be made prettier.

### Breaking Changes 

None

### Checklist

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2021-11-12 01:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/office-hours?pullRequest=593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/office-hours?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/office-hours?pullRequest=593) it.</sub>

2021-11-13 17:50 UTC, triple-jay requested changes
Thank you for making these changes Archit!! I did check that the year and term are now correct on the admin creation page---however, could you get rid of the input validation for just the course id? Usually, we structure our course ids like tc004-fa-21, which is the course code followed by the semester and then the year. Thus, the course ids are not integers. 

Other than that, thanks a lot for working on this!! You're really onboarding very fast :)

2021-11-13 17:57 UTC, Archit404Error commented
> Thank you for making these changes Archit!! I did check that the year and term are now correct on the admin creation page---however, could you get rid of the input validation for just the course id? Usually, we structure our course ids like tc004-fa-21, which is the course code followed by the semester and then the year. Thus, the course ids are not integers.
> 
> Other than that, thanks a lot for working on this!! You're really onboarding very fast :)

Got it! Would you like me to check whether the course id is in "tc004-fa-21" format or just remove validation for course id entirely?

2021-11-13 19:48 UTC, triple-jay commented
I think removing validation is fine :) it's just going to me mostly the PMs or I on the admin page so I think you're good!

2021-11-13 20:07 UTC, Archit404Error commented
Ok sounds good! I removed the course id validation and also just added in some validation to ensure year is a positive integer!

2021-11-14 18:30 UTC, triple-jay requested changes
Thanks for making that change! Just one more thing that I noticed:

I noticed that the course code asks for a 4-5 letter department. However, take CS 2110 for example. This takes a 2 letter department. Since it really depends on the department, I think it's fine to remove validation checks for this as well. Once that's done, I'll approve!

<img width="420" alt="Screen Shot 2021-11-14 at 1 28 44 PM" src="https://user-images.githubusercontent.com/40004551/141693755-b841313e-a452-4dcc-84eb-0927cf9b4587.png">

2021-11-15 16:52 UTC, triple-jay approved these changes
Thank you so much for working on this Archit!! It all looks good to me now. Make sure to pull from master to fix any potential merge conflicts before merging this branch in!

2021-11-15 21:14 UTC, merged