Calendar Export
cornell-dti/office-hours pull request #596
Opened 2021-11-24 02:22 UTC by danakim21

### Summary 

Changed side-view so that the circle button is below time and calendar export icon is added next to the name of the office hour. When a user clicks on the calendar export icon, a popup is opened. This shows two options -- Export to Google Calendar and Export to Apple Calendar. When Export to Google Calendar is clicked, a new event is added to the user's primary google calendar. When Export to Apple Calendar is clicked, an .ics file is downloaded so that the user can import it to their Apple Calendar. 

<img width="384" alt="Screen Shot 2021-11-23 at 9 12 31 PM" src="https://user-images.githubusercontent.com/48458175/143158944-402ddcaf-5dc1-4691-9175-d65e0108ed69.png">

<img width="1302" alt="Screen Shot 2021-11-23 at 9 15 13 PM" src="https://user-images.githubusercontent.com/48458175/143159250-b8bc4492-ae4b-4009-8b79-e91631d277e5.png">

### Test Plan 

- [ ] Test by exporting both Google and Apple Calendar for: 
  - [ ] TA view 
  - [ ] Professor view 
  - [ ] Student view 
- [ ] Check that location is correct for: 
  - [ ] Virtual 
  - [ ] Hybrid 
  - [ ] In-person 
- [ ] Check that other information is correct (Name, Time, Date)

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2021-11-28 01:59 UTC, triple-jay requested changes
Thank you so so much for working on this Dana!! This is definitely a **very challenging** task that I assigned you, and I appreciate you taking the initiative to learn a lot of this stuff on your own! I did test that the Apple Calendar export works as expected by clicking on the button to download the .ics file and dragging it into my calendar on my computer. However, the Google Calendar button does not work yet as far as I could tell. I know that you said you weren't finished with the PR when you messaged me, so it's totally fine if you didn't implement it yet :). Just letting you in the case that you did implement it so I could let you know it doesn't work yet on my end!

Regardless, thanks again for working on this, and **especially** for taking on the extra challenge to implement this with the Google API! It really makes me happy that you chose to go for the extra challenge because you thought it would be better for our users.

2021-12-10 23:37 UTC, pooja654 reviewed
This is really cool Dana! Your implementation looks really clean. I tested that the Apple Calendar export works (I successfully downloaded and added it to my calendar), and as Jeremy said, I noticed the Google Calendar one did not seem implemented yet.

One suggestion I have is to make the popup a little smaller and reduce the whitespace - I feel like it would look better.

2021-12-13 17:22 UTC, nada-attia reviewed
dana, good job with this pr! one suggestion: can you make the modal responsive on smaller screens? if u do cmd+option+j (assuming ur using chrome) and you click on the little phone icon you can see what the modal looks like on an iphone screen rn (its really big and you cant click the x button). 

you can refer to other existing modals when fixing this issue such as the popup that appears when you click leave queue. 

other than that great work dana :)

2021-12-13 17:25 UTC, nada-attia reviewed
dana, good job with this pr! one suggestion: can you make the model responsive on smaller screens? i u do cmd+option+j and you click on the little phone icon you can see how the modal looks like on an iphone screen rn (its really big and you cant click the x button). 

you can refer to other modals when fixing this issue such as the popup that appears when you click leave queue. 

other than that great work dana :)

2021-12-13 17:25 UTC, nada-attia commented on src/components/includes/CalendarExportModal.tsx
> +    // };
also make sure u delete comments before merging

2022-02-13 21:35 UTC, closed without merging