Not Working!
cornell-dti/office-hours pull request #600
Opened 2021-12-16 15:53 UTC by pooja654

### Summary 

### Test Plan 

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2021-12-16 23:05 UTC, triple-jay requested changes
See my attached comments for the code! I also attached a really helpful article that explains why you need to do it the way I mentioned :)

2021-12-16 23:05 UTC, triple-jay commented on src/components/includes/SessionView.tsx
> +                        <div className="button" onClick={() => gotItClicked}>
Remove the () => and just have onClick={gotItClicked}

Here's a good article that explains why :)

https://upmostly.com/tutorials/react-onclick-event-handling-with-examples

2021-12-16 23:05 UTC, triple-jay commented on src/components/includes/SessionView.tsx
> +                        <div className="button" onClick={() => enableClicked}>
Similarly here, remove the () => and just have enableClicked

2025-10-01 02:58 UTC, NIDHI2023 commented
Closing because I believe text notifs have been taken care of in https://github.com/cornell-dti/office-hours/pull/620!

2025-10-01 02:58 UTC, closed without merging