Merging (some) fall changes into release
cornell-dti/office-hours pull request #708
Opened 2023-01-19 23:10 UTC by abagel21

### Summary 

### Test Plan 

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2023-01-19 23:56 UTC, triple-jay approved these changes

2023-01-21 07:49 UTC, triple-jay approved these changes

2023-10-18 21:33 UTC, michelleli01 requested changes
Hi! I've begun to review this PR, but before I continue, could you please resolve this merge conflict and update the semester appropriate?

2023-10-18 21:33 UTC, michelleli01 commented on src/constants.ts
> +export const CURRENT_SEMESTER = 'SP23';
Should this be FA23 now? Please resolve the merge conflict for this PR

2023-10-18 21:33 UTC, michelleli01 commented on src/constants.ts
> +export const END_DATE = '2023-05-20'
These dates should be altered too right?

2024-04-19 20:19 UTC, merged