[DRAFT]: New collect feedback
cornell-dti/office-hours pull request #768
Opened 2023-11-01 16:56 UTC by rgu0114

### Summary 

New PR for [this ticket](https://www.notion.so/Star-rating-after-each-question-space-for-feedback-50f53284f184457badf24b5a72202de6) without all the annoying linting issues from [this PR](https://github.com/cornell-dti/office-hours/pull/761)

### Test Plan 

### Notes 

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2023-11-28 22:14 UTC, Sydney-tran reviewed
This PR looks really good so far! I think the feedback form will be very helpful for professors/tas. In terms of validation, I think students should be required to add a somewhat detailed explanation (one or two words shouldn't be enough) so maybe the code could enforce a minimum character/word count, but this can definitely be discussed more with everyone at standup. Also, once you finish up the styling and the PR as a whole, don't forget to remove the `console.log` statements. Besides that, very nice job!

2024-02-22 08:24 UTC, burninglilies requested changes
Great work so far! I don't see any bugs on my end when I run and test it for edge cases as well so far so the front end works perfect. But one thing to note is that the feedback is stored in courses and only the feedback rating and written feedback is stored. Sometimes there are multiple TA's that are assigned to a an office hours session and multiple sessions in a course so I think it would be beneficial to store the data on the student making the feedback and the TA receiving the feedback. And then maybe storing this in sessions instead of courses or as an alternative to this, store the session of the feedback in courses with the other information

2024-03-30 06:02 UTC, stevenyuser reviewed
This feature looks really good! I think the design looks pretty good and I tested it on my machine with two different accounts and it works. I also think it's a pretty useful feature for TAs, Professors, and students.

I have three possible suggestions about changing the functionality of the "Submit Rating" button. 
1. The button is clickable even when the conditions for valid feedback aren't fulfilled. Although this is visually shown to the user through the use of a grayed-out color for the button, the button isn't actually disabled. I recommend adding a `disabled` property to the button to fix this.
2. The logic for valid feedback is repeated and should probably be in its own function or state variable. This way, it will be easier to call the logic for if feedback is valid and it will also be easier to add more complex logic to see if feedback is valid.
3. Currently, feedback is only accepted if there is a rating and there's some text in the feedback box (length > 0). However, some students will probably only give a star rating to a TA and not write anything. I think that feedback should also be accepted, as it will probably be one of the most common forms of feedback.

2024-04-15 15:57 UTC, rgu0114 commented on src/components/includes/FeedbackPrompt.tsx
> +
Thanks for the feedback! These are definitely great points – I just pushed the new changes. I added the disabled property and only made the existence of `rating` a prerequisite for submitting feedback.

2024-04-16 05:47 UTC, burninglilies approved these changes
Thanks for making the changes Richard! I remember Alisha and Benji were the ones who suggested making comments on a review required to help collect extra feedback as justification to a star review. But we can leave it optional for now because of convenience purposes. 
Also, I tested for the same things as my original review and it looks good as well.

2024-04-16 20:08 UTC, merged