Made logo clickable to go to the home page
cornell-dti/office-hours pull request #790
Opened 2024-02-18 18:16 UTC by stevenyuser

### Summary 

Made the QMI logo clickable, so that when it is clicked, it redirects the user to the "/home" page.

<img width="1439" alt="image" src="https://github.com/cornell-dti/office-hours/assets/77898813/232e3a3d-69b2-44a1-b1ea-aa1df006cfe6">

<img width="1440" alt="image" src="https://github.com/cornell-dti/office-hours/assets/77898813/13697cde-138a-44ad-95ba-1627e2ad4ad2">

### Test Plan 

Tested clicking the logo on different screen sizes (mobile, computer, tablet).

### Notes 

Made the logo have an underline on hover. Also changed the user profile underline hover behavior to be consistent in style with the logo hover style.

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2024-02-18 22:08 UTC, rgu0114 commented on src/styles/TopBar.scss
> +        // .logo {
make sure to remove all comments before pushing

2024-02-18 22:53 UTC, rgu0114 requested changes
This looks great Steven! Thanks again for taking this on and for making sure to test on tablet, mobile, etc. We may want to check with design/product on the color of the underline, and make sure to remove commented out code. I'll approve as soon as those two things are resolved.

2024-02-19 01:01 UTC, stevenyuser commented
Thanks for the feedback, Richard! I just removed the commented-out code.

2024-02-22 08:33 UTC, burninglilies approved these changes
Thanks for the changes Steven, I double checked the hover coloring for the logo shadow and it's consistent with the user profile hover. So looks good!

2024-02-22 21:54 UTC, rgu0114 approved these changes

2024-02-22 22:08 UTC, merged