CSV Export
cornell-dti/office-hours pull request #803
Opened 2024-03-01 22:54 UTC by stevenyuser

### Summary 

- in professor dashboard, added option to let staff export queue data/statistics on sessions
  - the user can select which statistics to export
- The queue data is downloaded on the user's local computer as a CSV file

Demo:
https://github.com/cornell-dti/office-hours/assets/77898813/5e34b649-523b-4872-a9d0-f0c0c52fc7e0

Screenshot:
<img width="1440" alt="image" src="https://github.com/cornell-dti/office-hours/assets/77898813/0e0ab426-f6cf-43de-8c9c-334f5b473cae">

### Documentation:

- relevant documentation is in code (ExportCSV.tsx)

### Test Plan 

- Check that the exported data matches the firebase data
- Check that only the selected analytics get exported to the CSV file

### Notes 

Future changes

- Need to add a date picker once QMI's material-ui library is updated to v5 (and material-ui x-date-pickers v5 is added to dependencies), right now only selecting by semester works (the date picker option is just a placeholder)
- Implement exporting rating analytics after [rating feature](https://github.com/cornell-dti/office-hours/pull/768) is merged into main branch and ready

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2024-03-14 19:15 UTC, rgu0114 requested changes
Hey Steven, great progress on this task since the last time I saw it at work session – sorry for the slow turnaround for code reviews recently. You've made quick progress on this, and the functionality looks good overall – no issues with the frontend at all. A few comments:

1. The average wait time is off by a bit (is this rounded?). When I tested it, the question was answered ~1 minute after it was added.
<img width="903" alt="Screen Shot 2024-03-14 at 3 05 14 PM" src="https://github.com/cornell-dti/office-hours/assets/100158738/9177638e-0d47-4a11-8cf9-491f09c6e219">
2. This data was nice to see! Small nit though, there's several NaNs so let's have that default to something more user friendly
<img width="914" alt="Screen Shot 2024-03-14 at 3 07 46 PM" src="https://github.com/cornell-dti/office-hours/assets/100158738/fadca523-da25-4f72-8b82-9abf6a236306">
3. Could you investigate why the TA names/net IDs are blank in some spots? It's hard to identify as a professor if it's bc it's the same TAs as previous sessions or there's some issue.
4. I see that you're holding off on adding the date picker for now. I don't quite remember what we discussed – were you able to find reasonable options from other libraries, or should we upgrade to MUI v5 first?


That's all the suggestions I have for now. We can talk more during work session about these things + future changes. Great work!

2024-03-14 19:16 UTC, rgu0114 reviewed
Also I think you may have attached the wrong demo recording lol

2024-03-15 02:33 UTC, rgu0114 commented on src/components/includes/ExportCSV.tsx
> +            const sessionWaitTime = isNaN(waitTime) ? "" : Math.round(waitTime).toString();
changes for NaN look good, wouldn't have done it any other way

2024-03-28 01:48 UTC, stevenyuser commented
Hi Richard, I finished the date picker and addressed the other bugs/fixes as well!

2024-09-18 05:05 UTC, rgu0114 approved these changes
Whoops, forgot to give this another pass at the end of last semester, but this looks good + I remember we discussed the comments during work session.

2024-09-18 22:05 UTC, merged