[Draft] Aggregate Wrapped user data
cornell-dti/office-hours pull request #874
Opened 2024-10-13 01:39 UTC by NIDHI2023

### Summary 

- Building on [this PR](https://github.com/cornell-dti/office-hours/pull/870), adds total time TAs helped students, a user's most visited OH id, and most visited TA id as part of the wrapped data
- Adds extra check when pushing to Wrapped collection that user must be active
- Also rounds some of the time-related numbers to ensure integer results

### Test Plan 

- Case of inactive student/TA should not be added to wrapped collection
- Total time should be an integer always
- Ensure the favorite OH and TA is accurate
- Ensure nothing breaks with undefined values

### Notes 

- currently in process of testing
- Currently gets favorite OH and favorite TA as separate calculations, so the end TA might not be part of the OH session. This should be adjusted based on desired output

### Breaking Changes 

None

- [x] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2024-10-18 21:58 UTC, rgu0114 reviewed
left a couple comments

2024-10-18 21:58 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +        } else if (userStats[answererId] && userStats[answererId]?.timeHelpingStudents === undefined) {
Is this `else if` redundant?

2024-10-18 21:58 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +
since there's a one to one mapping between `sessionId` and a single OH visit, I think you can just collect all the visited sessionIds and get the length of that at the end for # of OH visits

2024-10-18 21:58 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +
yea for this I think it's ok if not every session has TAs assigned

2024-10-18 22:04 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
>  const startDate = admin.firestore.Timestamp.fromDate(new Date('2023-08-20'));
remember to change these dates to sp24 and fa24

2024-10-18 22:11 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +
to answer your question, let's use most common `answererId` for a student as a proxy for their favorite TA since there's many courses that don't assign TAs to office hours in QMI and work backwards from there to determine favorite class and day of the week since class should correspond with favorite TA. We can get class pretty easily from sessionId, but maybe we run a separate script to label each session with a day of the week – we'll leave day of the week for later.

2024-10-19 00:59 UTC, NIDHI2023 commented on src/scripts/wrapped-fa24.ts
> +        } else if (userStats[answererId] && userStats[answererId]?.timeHelpingStudents === undefined) {
I was thinking of the case where while iterating through questions, a user who is actually a ta comes up first as the asker, so they get an instance created without the timeHelpingStudents (as undefined). Then if they come up later as an answerer, indicating that they are a ta, the if statement only checks and gives all the fields if the ta doesn't already have an instance, so I think they wouldn't actually get the timeHelpingStudents field without this extra check.

2024-10-19 18:37 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +        } else if (userStats[answererId] && userStats[answererId]?.timeHelpingStudents === undefined) {
oh i see

2024-10-27 21:07 UTC, rgu0114 requested changes
At this point, now that the functionality is more or less there I think it'll be helpful to start thinking about code style and readability – which should also make verification a bit easier as we get into the last few weeks of development.
1. Separating concerns into helper functions, for example async functions handling processSessions(answererId, sessionId) and updateWrappedDocuments().
2. `await` can sometimes be inefficient when repeatedly called, and we should start thinking a bit more about performance for this script. It might be better to do something like the following: `const sessionPromises = questionsSnapshot.docs.map(doc => sessionsRef.doc(doc.sessionId).get());`
`const sessionDocs = await Promise.all(sessionPromises);`
Of course, this is made difficult when we're (more intuitively) iterating through questions, which each have their own sessionId, so one possibility would be to do some pre-processing to group questions with the same `sessionId` together beforehand so we can do this type of batch processing.
3. Using a `for...of` loop is generally better for async operations. So for the loop at the end where we use `userStats` to update the `Wrapped` collection, you might do something like `for (const [userId, stats] of Object.entries(userStats)) {`.
4. For all error scenarios, especially since we'll be rolling this out to production soon, let's collect all `userIds` in a separate list and log those out at the end so we can investigate any issues more easily.

Try to refactor the code and make these changes incrementally, testing as you go along.

2024-10-27 21:16 UTC, rgu0114 requested changes
A couple small things to improve code maintainability

2024-10-27 21:16 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +            if ((stats.numVisits > 0)
This is a confusing conditional. Let's make it something like:
```
const hasVisits = stats.numVisits > 0;
const isTaActive = stats.timeHelpingStudents !== undefined || (TAsessions[userId]?.length > 0);
const hasFavoriteTa = stats.favTaId !== "";

if (hasVisits && isTaActive && hasFavoriteTa) {
```

2024-10-27 21:16 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +        if (!officeHourSessions[askerId]?.includes(sessionId)) {
this might lead to a weird edge case error if `officeHourSessions[askerId]` is undefined since we're using optional chaining (`?.`). Let's make this: 
`officeHourSessions[askerId] = officeHourSessions[askerId] || []; 
if (!officeHourSessions[askerId].includes(sessionId)) {
    officeHourSessions[askerId].push(sessionId);
}`

2024-10-27 21:31 UTC, rgu0114 commented on src/scripts/wrapped-fa24.ts
> +        if (stats.favTaId && stats.favTaId !== "") {
this block of code getting the user's favorite class and title seems correct and precise to me, but is it a bit inefficient? For instance, if we've already identified the favorite TA, there should only be one class/title and we don't need to do all this ordering. Idk, there might just be some edge cases I haven't thought of.

2024-11-01 20:40 UTC, NIDHI2023 commented on src/scripts/wrapped-fa24.ts
> +        if (stats.favTaId && stats.favTaId !== "") {
I mainly included this extra if statement because I wasn't sure if it was possible for a user to encounter the same TA in two classes. But if we can confirm that a student always has one class in common with the favorite TA and is a guaranteed precondition, I definitely agree that this isn't needed.

2025-09-15 02:50 UTC, closed without merging