edit classes frontend redesign
cornell-dti/office-hours pull request #887
Opened 2024-11-07 01:56 UTC by swang235

### Summary 
Update of edit classes page:

current design:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/8dd619a6-4c66-49c3-ba53-13390e2f4775">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/a8c148d4-aedc-4b69-9e0a-7079fc32531c">

redesign:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/db91b102-4a2a-467b-bccb-87bb2fa8665f">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/938ee9e7-89f7-40b6-a9da-d207b4871b0b">

### Test Plan

- testing different cases (ex class pairings, roles, search bar)
- tested responsiveness for ^ as well

### Notes 

### Breaking Changes 

None

- [x ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2024-11-17 15:04 UTC, NIDHI2023 reviewed
This is a really nice redesign! It looks so much more cleaner. I have a few suggestions you could add:
- When searching for a class that doesn't exist, maybe add some padding between the label thing and the end of the white part so it doesn't look too crammed together

![image](https://github.com/user-attachments/assets/643ececc-2b07-4827-8973-72139739bf4b)

- I think making the Go to Course buttons more visible by changing the color or adding a border or something else would be good. And also maybe adding more padding again to make the class cards look more vertically symmetric 

![image](https://github.com/user-attachments/assets/f6d06177-0c9c-4b83-a99b-c6ac3a7f8d41)

2024-12-05 19:33 UTC, rgu0114 requested changes
<img width="1252" alt="Screen Shot 2024-12-05 at 2 33 08 PM" src="https://github.com/user-attachments/assets/97928323-89de-4998-b2a7-1a3c71bd2e55">

It seems like only non-prof courses have the hover shadow effect. Is this intended? The prof courses are clickable but don't have any effect.

2024-12-05 21:56 UTC, rgu0114 requested changes
I think the font of the search bar placeholder text can also match more closely
<img width="1358" alt="Screen Shot 2024-12-05 at 4 56 03 PM" src="https://github.com/user-attachments/assets/05afa697-0ee3-4b33-b9be-a7dda2a13bdb">
<img width="882" alt="Screen Shot 2024-12-05 at 4 56 19 PM" src="https://github.com/user-attachments/assets/bb707e13-b7d8-49bb-a8c4-0d4ef3b5b1de">

2024-12-06 06:46 UTC, rgu0114 requested changes
just a couple more minor things, everything else looks good!

2024-12-06 06:46 UTC, rgu0114 commented on src/components/includes/CourseCard.tsx
> +    let selectedBackgroundColor = "#F5F5F5";
oh can we put these in the associated .scss file?

2024-12-06 06:46 UTC, rgu0114 commented on src/components/includes/CourseCard.tsx
> +                    <></>
nit: let's avoid empty components `<></>` and use `&&` where we can, assuming that has the same behavior

2024-12-06 06:46 UTC, rgu0114 commented on src/components/includes/CourseCard.tsx
General: non prof/ta former classes still seem to have the hover effect (benji 2110) when idt they should
<img width="1234" alt="Screen Shot 2024-12-06 at 1 44 37 AM" src="https://github.com/user-attachments/assets/8f6af2bb-feb7-47d7-be22-1cc2d1efd598">

2025-03-02 21:36 UTC, laylaliuuu commented on src/components/includes/CourseCard.tsx
> +    let selectedBackgroundColor = "#F5F5F5";
There are a few lines that I'm unsure if it's intentional or could be repetitive, what does selected-background-color do, and why does only student role have this background in the if else: 

 .scss:
   selectedBackgroundColor-role-student: "rgba(214, 234, 254, 0.4)"; 
    selectedBorderColor-role-student: "#77BBFA";

    &.selected {
        background-color: rgba(214, 234, 254, 0.4);
        border: 2px solid #77BBFA;
    }
    
    .tsx:
if (role === "ta") {
        roleString = "TA";
        roleColor = "#var(role-color-ta)";
    } else if (role === "professor") {
        roleString = "PROF";
        roleColor = "#var(role-color-professor)";
    } else {
        selectedBackgroundColor = "selectedBackgroundColor-role-student";
        selectedBorderColor = "selectedBorderColor-role-student";
    }

2025-03-12 16:53 UTC, merged