Wrapped emailing [Draft]
cornell-dti/office-hours pull request #913
Opened 2024-12-04 18:08 UTC by NIDHI2023

### Summary 

### Test Plan 

### Notes 

- In the prod database would need to also update indexes for user like below:
![image](https://github.com/user-attachments/assets/8b999a67-135e-478a-8bb1-096a4e930c5d)
Firebase auto-generates this when you run the script and get an initial error message with a link:
![image](https://github.com/user-attachments/assets/22dcc3df-71c2-4df2-96d6-964ad317dac1)
Should look like this at the end and script should be working
![image](https://github.com/user-attachments/assets/78760617-4e15-4948-80c0-086244bd995b)

### Breaking Changes 

None

- [ ] I have updated the documentation accordingly.
- [ ] My PR adds a @ts-ignore

2024-12-04 19:14 UTC, rgu0114 requested changes

2024-12-04 19:14 UTC, rgu0114 commented on src/scripts/wrapped-email.ts
> +// const resend = new Resend('re_123456789');
o remember to stash this in a .env if this is your resend api key

2024-12-04 19:15 UTC, NIDHI2023 commented on src/scripts/wrapped-email.ts
> +// const resend = new Resend('re_123456789');
it's not, just a default test!

2024-12-20 03:39 UTC, rgu0114 reviewed
Nice job testing this thoroughly and documenting your process well

2024-12-20 04:23 UTC, rgu0114 reviewed
Great work with this and figuring out the Resend API! No glaring issues I can see with this – only thing to watch out for when we run it is if we hit a limit, what's the best way to continue where we left off (if manually doing it is the best option, that's ok too).

2025-02-04 02:07 UTC, closed without merging